name: l10n_generator
description: Service to generate Flutter localization files
version: 1.0.0
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  archive: ^3.4.0
  path: ^1.8.0
